### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method DI\Container::withHeader()

### ISSUE THREAD

**Issue by pbreah** [tuupola/slim-jwt-auth#188]
Here are the settings used:

```php
$settings =  [
   'secret' => 'shh-this-is-the-secret',
   'path' => ['/link'],
   'attribute' => 'jwt',
   'secure' => true,
   'relaxed' => ['localhost'],
   'error' => function ($response, $arguments) {
        $data = [];
        $data['status'] = 'error';
        $data['message'] = 'An Error Ocurred, please try again later';
         return $response
              ->withHeader('Content-Type', 'application/json')
              ->getBody()->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    },
];
```

### Problem

When the code runs it gets back an error with the error below. I copied the error callback exactly as on the documentation, and just changed the error message. So it seems it is an instance of the container object rather than the response object being passed to the callback (the reason why the ::withHeader() is undefined)

I hope you can replicate the problem with this.

Using:

PHP 7.3.11

composer.json (require section):
```json
{
    "require": {
        "php": "^7.2",
        "ext-json": "*",
        "firebase/php-jwt": "^5.2",
        "hybridauth/hybridauth": "^3.3",
        "monolog/monolog": "^2.1",
        "php-di/php-di": "^6.1",
        "slim/psr7": "^1.1",
        "slim/slim": "^4.5",
        "slim/twig-view": "^3.0",
        "tuupola/slim-jwt-auth": "^3.4"
    },
}
```
Error:
```
Fatal error: Uncaught Error: Call to undefined method DI\Container::withHeader() in /path-to-project/app/settings.php:27 
Stack trace: #0 [internal function]: {closure}(Object(DI\Container), Object(DI\Definition\FactoryDefinition)) 
#1 /path-to-project/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array) 
#2 /path-to-project/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call(Object(Closure), Array) 
#3 /path-to-project/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array) 
#4 /path-to-project/vendor/php-di/php-di/src/Definition/Resolver/ArrayResolver.php(62): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition)) 
#5 /path-to-project/vendor/php-di/php-di/src in /path-to-project/app/settings.php on line 27
```

**Comment by tuupola** [comment]
To me it looks like this has nothing to do with the middleware. Instead it has something to do with the `settings.php` file and how it is parsed. Error message also supports this conclusion. Middleware is not executed, error comes when parsing `settings.php`. 

Try to do as [README suggests](https://github.com/tuupola/slim-jwt-auth#error).

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
    "secret" => "supersecretkeyyoushouldnotcommittogithub",
    "error" => function ($response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->getBody()->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));
```

If this works then try to debug why in `settings.php` the `$response` variable is expanded to `DI\Container`.
