### ISSUE TITLE
Download file problem using the middleware

### ISSUE THREAD

**Issue by realrecordzLab** [tuupola/slim-jwt-auth#199]
I have some problems when I try to download a random named file. The Slim app was working fine befor the implementation of the JWT middleware, now I get a 500 error when chrome try to download the file. I'm passing the `Authorization` header but it seems that the server isn't able to serve the file because the JWT middleware try to find a route, but in this case it's a file to be served not a route.  Here is the heroku log. Is there a fix for this, maybe a rule that I can use to avoid this problem?
```
2020-11-25T11:55:35.846418+00:00 app[web.1]: [25-Nov-2020 11:55:35 UTC] PHP Fatal error:  Uncaught Slim\Exception\HttpNotFoundException: Not found. in /app/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:91
2020-11-25T11:55:35.846484+00:00 app[web.1]: Stack trace:
2020-11-25T11:55:35.846776+00:00 app[web.1]: #0 /app/vendor/slim/slim/Slim/Routing/RouteRunner.php(72): Slim\Middleware\RoutingMiddleware->performRouting()
2020-11-25T11:55:35.846999+00:00 app[web.1]: #1 /app/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php(132): Slim\Routing\RouteRunner->handle()
2020-11-25T11:55:35.847169+00:00 app[web.1]: #2 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Tuupola\Middleware\JwtAuthentication->process()
2020-11-25T11:55:35.847335+00:00 app[web.1]: #3 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
2020-11-25T11:55:35.847472+00:00 app[web.1]: #4 /app/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
2020-11-25T11:55:35.847624+00:00 app[web.1]: #5 /app/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
2020-11-25T11:55:35.847704+00:00 app[web.1]: #6 /app/index.php(112): Slim\App->run()
2020-11-25T11:55:35.847730+00:00 app[web.1]: #7 {main}
2020-11-25T11:55:35.847873+00:00 app[web.1]: thrown in /app/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 91
2020-11-25T11:55:35.848329+00:00 app[web.1]: 10.33.39.40 - - [25/Nov/2020:11:55:35 +0000] "GET /113c6fe0d26f7c9c.mfs HTTP/1.1" 500 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
```

**Comment by tuupola** [comment]
Does the file `$DOCUMENT_ROOT/113c6fe0d26f7c9c.mfs` exist? If not then the default setup of Slim will try to execute that URL as a route.

**Comment by realrecordzLab** [comment]
> Does the file `$DOCUMENT_ROOT/113c6fe0d26f7c9c.mfs` exist? If not then the default setup of Slim will try to execute that URL as a route.

yes, the file is saved on heroku server before the response is passed to the client. I'm using the `chrome.downloads` api so I'm passing the url to the `download()` method of the api and before implementing the authentication the files were downloaded correctly. To solve this problem I've created a new endpoint `$app->get('/{filename}')` but I don't like this solution and I don't understand why this beahviour after middleware implementation

**Comment by tuupola** [comment]
WIth the usual setup Slim should not even execute when downloading a static file. With Apache this is done with `RewriteCond %{REQUEST_FILENAME} !-f` with Nginx this is done with `try_files`.

https://www.slimframework.com/docs/v4/start/web-servers.html

I do not use Heroku so I do now know why Slim is executed even when downloading static files. Another workaround would be to save the static files to forlder called `download` and ignore that in the middleware config. Proper solution IMO would be to not execute PHP at all when accessing static files, unless the download has to be authenticated of course.
