### ISSUE TITLE
Add error callback for 1.x Branch

### ISSUE THREAD

**Issue by git-slim** [tuupola/slim-jwt-auth#42]
I tryed to add an error callback to the 1.x branch and it worked on my local server but when I uploaded it on an another one i got an slim error. 
PHP Version is the same (5.6).

This code I added in jwtAuthetification.php @ line 99

```
if (false === $decoded = $this->decodeToken($token)) {
    if (is_callable($this->options["error"])) {
        $params = array("decoded" => $decoded, "app" => $this->app);
        if (false === $this->options["error"]($params)) {
            $this->app->response->status(401);
            $this->error(array(
                "message" => "Callback returned false"
            ));
            return;
        }
    }

    $this->app->response->status(400);
    $this->error(array(
        "message" => $this->message
    ));
    return;
}
```

then my JwtAuthetification setup looks like this:

```
$app->add(new JwtAuthentication([
    "secret" => $app->config->get('jwt.secret'),
    "secure" => false,
    "relaxed" => ["localhost","www"],
    "path" => ["/edition","/photos","/files","/issues"],
    "callback" => function ($options) use ($app) {
        $app->jwt = $options["decoded"];
    },
    "error" => function ($options) use ($app) {
        $app->setCookie('deeplink', $_SERVER['REQUEST_URI'] );
        return $app->redirect( $app->urlFor('index') );
    }
]));
```

and thats the error I get on the other server

```
Details

Type: Slim\Exception\Stop
File: /homepages/htdocs/app/vendor/slim/slim/Slim/Slim.php
Line: 1022
Trace

#0 /homepages/htdocs/cypos/vendor/slim/slim/Slim/Slim.php(1042): Slim\Slim->stop()
#1 /homepages/htdocs/cypos/vendor/slim/slim/Slim/Slim.php(1105): Slim\Slim->halt(302)
#2 /homepages/htdocs/cypos/php/start.php(137): Slim\Slim->redirect('/')
#3 /homepages/htdocs/cypos/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php(104): {closure}(Array)
#4 /homepages/htdocs/cypos/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\JwtAuthentication->call()
#5 /homepages/htdocs/cypos/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#6 /homepages/htdocs/cypos/php/start.php(163): Slim\Slim->run()
#7 /homepages/htdocs/cypos/public/index.php(2): require('/homepages/33/d...')
#8 {main}
```

I currently cant migrate to slim3 to upgrade this middleware to 2.x.

**Comment by tuupola** [comment]
You do not need to modify the middleware. It already supports error callback.

**Comment by git-slim** [comment]
Realy? But in the Documentation it's only written that that `the server will respond with 401 Unauthorized`In the 2.x Branch it have a error callback.
What I would like to achieve it that it redirects to an another route when the jwt is not valid

**Comment by tuupola** [comment]
README for 1.x seems to be missing error callback. However the [code is there](https://github.com/tuupola/slim-jwt-auth/blob/1.x/src/JwtAuthentication.php#L142-L152). I have not tested, but what you are doing looks like it might work.

``` php
$app->add(new JwtAuthentication([
    ...
    "error" => function ($options) use ($app) {
        $app->redirect($app->urlFor("index"));
    }
]));
```
